name: "Terragrunt Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  working_dir: IaC/production/homelab

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hcl fmt --check --diff'

  deploy:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::716182248480:role/Github-TF-State
          role-session-name: github-actions-session

      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Install Terragrunt and OpenTofu
        uses: gruntwork-io/terragrunt-action@v3

      - name: Run terragrunt apply
        working-directory: ${{ env.working_dir }}
        run:
          terragrunt run apply -all --non-interactive
