name: "Terragrunt Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'IaC/**'
      - '.github/workflows/deploy.yml'

permissions:
  contents: read
  id-token: write

env:
  working_dir: IaC/production/homelab

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@95fc057922e3c3d4cc021a81a213f088f333ddef # v3
        with:
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hcl fmt --check --diff'

  deploy:
    runs-on: ubuntu-latest
    needs: [ checks ]
    concurrency:
      group: terragrunt
    steps:
      - name: 'Checkout'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::716182248480:role/Github-TF-State
          role-session-name: github-actions-session

      - name: Tailscale
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}
          tags: tag:ci
          statedir: /tmp/tailscale-state/

      - name: Setup kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@95fc057922e3c3d4cc021a81a213f088f333ddef # v3
        with:
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run --all --non-interactive -- apply'
          tg_comment: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
