name: "PR Agent"

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: write # for qodo-ai/pr-agent to create pull requests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - main

jobs:
  check:
    uses: qodo-ai/pr-agent@0
    with:
      checkov: false
      merge-checks-timeout: 300
