name: "AI Review"

on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]
  issue_comment:

jobs:
  ai-review:
    permissions:
      issues: write
      pull-requests: write
      contents: read
    uses: stuhlmuller/workflows/.github/workflows/review-bot.yml@main
    secrets: inherit
    with:
      model: "qwen.qwen3-coder-30b-a3b-v1:0"
